In [50]:
# 라이브러리 임포트
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
import seaborn as sns

In [ ]:
#머신러닝 모델링을 위한 Scikit-Learn 의 일부 기능 임포트
from sklearn.model_selection import train_test_split


In [4]:
print('라이브러리 임포트 완료')

라이브러리 임포트 완료


#### NumPy-배열기반데이터처리
-numpy: 라이브러리(만들어져 있는놈[함수]), ndarray-다차원배열\
-object: 속성,메소드

<numpy 사용이유>\
    1.속도빠름\
    2.메모리호율성 좋음(단 "테이터타입 동일해야함" , 연속공간) why 주소연산가능 like C언어\
    3.브로드캐스팅: for문 필요 X \
    <결론>numpy 써라잉

#### <Numpy ndarray 객체>

- 0차원 배열: 스칼라(단일값)
- 1차원 배열:벡터(vector) , 축1개
- 2차원 배열:행렬(Matrix) , 축2개
- <주의>1~3차원 배열 다 tensor라고 함 /tesor(Tensorflow,pytorch):차원을 개념화 시킨것 

- tensor(차원) : 2가지 관점에서 봐야함
    - 차원(축)의 갯수 :Rank
    - 선형대수(Rank)

- 일반적인 차원 Rank(축갯수)
    - Rank0 : 스칼라
    - Rank1 : 벡터
    - Rank2 : 행렬
    - Rank3 : tensor
    - Rank4

- 선형대수에서의 Rank: 선형독립적인 정보의 수
    - Linear Independence(선형 독립)
    - =어떤 벡터가 다른벡터의 조합으로 표현될 수 없으면 해당벡터를 선형독립하다.
    - <주의>선형대수에서 벡터는 점 , 신경망도 공간안에서 점이다!
    - span: 어떤벡터가 다른벡터에 의해서 생성 또는 합해질 수 있다.
    - 선형종속됬다: 새로운 데이터가 아니라 ,a,b벡터가지고도 c벡터만들수 있다.
    - 선형독립(rank):선형독립된것(새로운거, a-b조합해서 새로만들수 없는것)를 찾는것
    - 선형독립: 다른벡터들로 설명이 안되는거
    - <결론>종속:정보량 작고, 독립:정보량 많다.

- 기저벡터 :선형 독립이고,공간을 만드는 최소한의 벡터
    - <참고>신경망에서 hidden layer주는 이유
- 근데, 딥러닝에서는 축의 갯수가 의미가 없다.

In [ ]:
# ndarray 생성
# 1차원 배열 생성

array1 = np.array([1,2,3]) # array함수로 배열 생성
print(type(array1))
print(array1.shape) #배열의 모양을 "튜플"로 출력 / 튜플 = 인덱스
print(array1.ndim)  # 차원수(축의 갯수) 출력

<class 'pandas.core.arrays.integer.IntegerArray'>
(3,)
1


In [12]:
# 2차원 배열 생성
array2 = np.array([
    [1,2,3],
    [4,5,6]
])
print(array2.shape)
print(array2.ndim)

(2,)
1


In [25]:
# 또다른 형태의 2차원 배열
array3 = np.array([
    [[1,2,3]]
])

print(array3.shape) #프린트하면 그 값만 찍는다.
print(array3.ndim)

(1,)
1


In [26]:
# 데이터타입 =>dtype
list1 = [1,2,3]
array1 = np.array(list1, dtype = 'float16') # 따로 dtype = 'int16' 설정가능
# 나주엥 큰문제 될 수 있음 fpㄱ ㅏㅂ승로
print(array1.dtype)

float16


In [53]:
# 문자열이 포함된 리스트로 생성
list2 = [1,2.,3,'t'] #데이터 하나라도 소수점이 들어가면 float 로 바뀜
                    # 문자열 하나라고 있으면 유니코드 나옴
array2 = np.array(list2)
print(array2.dtype)

<U32


In [34]:
list3 = [1,2,3.]
array3 = np.array(list3)
print(array3.dtype)

Float64


In [46]:
#[형변환] dtype변경필요할때 : astype(): method 
# 꽤 많이 사용함
array_int = np.array([1,2,3])
print(array_int.dtype)

# int64 -> float 64로 바꾸기
array_float = array_int.astype('float64') #오브젝트 안에 있는 method 다
                                          #'float'문자열로 인식하게 해줘야 key가 됨
print(array_float.dtype)   #int -> float64로 바꾸기

# float64->int32 : 소수점 이하가 버림됨(엄청 중요함~)
array_float1 = np.array([1.1,2.7,3.5,])
print(array_float1.dtype)
array_int1 = array_float1.astype('int32') # int로 바꾸는순간 소수점 다 날라감
print(array_int1)

Int64
float64
Float64
[1 2 3]


In [58]:
# ndarray생성 함수
# array(list)
# arrange(start,stop,step)
seq_array = np.arange(10)
print(seq_array,type(seq_array))
# zero(shape)
zero_array1 = np.zeros((3,),dtype = 'int32') # 1차원 배열 # dtype = 'int32' 해줘야지 정수형태로 반환됨
print(zero_array1)

# zero_array2 = np.zeros((3,2)) # 2차원 배열 
# print(zero_array2)

# zero_array3 = np.zeros((3,2,3)) # float64
# print(zero_array3)

# ones(shape)
one_array = np.ones((3,)) # 길이가 3인 1차원 배열 만들고 모든값을 1.0으로 채워라
print(one_array)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0 0 0]
[1. 1. 1.]


In [66]:
# 배열의 형태 변경 메소드 : reshape(변경할 shape)-메소드, 배열 형태(shape) 변경
array1 = np.arange(10)
print(array1)

# 2X5 형태의 2차원 배열로 변경
array2 = array1.reshape(2,5) # (2,4)는 갯수안맞아서 안됨
                             # (5,2)는 5행 2열로 가능함
print(array2)                  

# 다시 원래대로 돌리기
array3 = array2.reshape(10,) #2차원을 1차원으로 변경(=행/열 개념이 없는 1차원 배열) 
                            # (10행 0열로 바꾸라는 의미 X)
                            # (10,1) -> 10행 1열 나옴     
                            #[0 1 2 3 4 5 6 7 8 9]:1행10열의 2차원 배열로 보일수 있지만 실제로는 1차원 배열
print(array3)


[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [75]:
# reshape: -1 인자 사용
array1 = np.arange(45)
print(array1) 

arr2 = array1.reshape(-1,5) #열은 5로 고정하고, 행은 컴퓨터 너가 알아서 계산해줘~
print(arr2.shape)

arr3 = array1.reshape(5,-1) # 행은 고정하고 열은 컴퓨터가 알아서 계산해줭~~
print(arr3.shape)

# 1차원 2차원으로 변경 : reshape(-1,1)
# 쓰는이유: 어떤함수는 파라미터()를 무조건 리스트로만 달라고 할때가 있음 그럴땐 사용
# 리스트로 달라고 했는데 단일값(스칼라) 주면 큰일남~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arr1 = np.arange(5) # 단일값 정리
print(arr1)

arr2 = arr1.reshape(-1,1)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]
(9, 5)
(5, 9)
[0 1 2 3 4]
[[0]
 [1]
 [2]
 [3]
 [4]]


In [91]:
# 3.4 인덱싱: 데이터 선택할때 사용
arr1 = np.arange(1,10) # 마지막10은 사용안함
print(arr1)
value = arr1[2]
print(value)

# 맨 뒤의 값 추출
print(arr1[-1])

# 맨뒤에서 두번째 값 추출
print(arr1[-2])

# 값 변경
arr1[0]= 9
print(arr1)

# 2차원에서 인덱싱
arr2d = np.arange(1,10).reshape(3,3) # 3X3으로 바꾸기
print(arr2d)
print(arr2d[0,1]) # arr2d[행,열]

# 2차원 슬라이싱






# 책에 있는 코드는 그냥 외울정도로 다 해야함


[1 2 3 4 5 6 7 8 9]
3
9
8
[9 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [103]:
# 1차원 슬라이싱
arr1 = np.arange(1,10)
print(arr1)
print(arr1[0:3]) #결과물 [1 2 3]
print(arr1[3:])
print(arr1[:]) # 전체:- 새로운 배열을 만든 것처럼 보이지만, 경우에 따라 원본과 메모리를 공유
# arr2 = arr1[:] # 
arr2[0] = 9
print(arr1) #결과: a2만 0이 바뀌었는데 a2도 같이 바뀜
            #이유: numpy는 원본이 바뀜, 그래서 원본이 바뀜
            # 
print(arr2)

# .copy: 원본변경되지 않게 copy 해야함 


# 2차원 슬라이싱


[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[9 2 3 4 5 6 7 8 9]


In [ ]:
# 2차원 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)
print(arr2d[0:2,0:2]) # 2차원 반환
print(arr2d[1:,:])  # 2차원 배열
# [1:,:] : 슬라이싱 표현
# :1 행기준(1번~끝까지 행)(0번째 행 제외)
# : 열기준(전체열)




# 주의: 지금하고 있는건 numpy 다(판다스에선 loc사용하셈~ 행,렬 접근할려면)
# 데이터다룰땐 pandas가 편하다.


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


C:\big20\ml_dev\Copilot_VLAbYfWU62.png

In [ ]:
# 팬시 인덱싱 : 연속되지 않는 여러개 선택
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)
print(arr2d[:2,2:3])# [3][6] 가져오기
print("=========================================")
print(arr2d[[0,2],2])  # 2차원 배열에서 0,2번째행의 2번째 열(인덱스2) 만 가져와라

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3]
 [6]]
[3 9]


In [133]:
# 불린 인덱싱(진짜 중요함)
arr1d = np.arange(1,10)
print(arr1d)
print(arr1d > 5)

print(arr1d[arr1d > 5]) # print(arr1d > 5) 에서True 만 뽑는다.


[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [ ]:
# 3.5 배열 정렬 - sort(): 정렬, argsort() : 정렬한 인덱스 반환
# sort() 
# 1.np.sort(ndarray) : 원본배열은 그대로 두고, 정렬된 새로운 배열을 반환
org_arr = np.array([3,1,9,5])
sorted_arr = np.sort(org_arr) 
print(f'원본 배열: {org_arr}')
print(f'정렬 배열: {sorted_arr}')
# 결국np.sort는 원본은 바뀌지 않는다.

# 2.ndarray.sort() : 원본 배열 정렬 (즉 원본이 바뀜)
print(org_arr.sort())  #결과 :원본을 바꿨기때문에 반환할게 없다.None
print(org_arr) # <주의>:오름차순 ascending 만 가능함

# 3.DESC[row:col:step] : [::-1] 즉 step 이 -1로 바뀜(뒤에서 가져와라)
sorted_arr = org_arr[::-1]
print(sorted_arr)

# 주의: 1차원에서 sort는 조심해야함!~~~ 따로따로 분류됨


원본 배열: [3 1 9 5]
정렬 배열: [1 3 5 9]
None
[1 3 5 9]
[9 5 3 1]


In [143]:
# 2차원 정렬:축이 존재한다.
arr2d = np.array([
    [8,12],
    [7,1]
])
print(arr2d)
np.sort(arr2d) # axis=1이 디폴트로 설정됨
np.sort(arr2d,axis=0) # 조심하기! 컬럼별로 sort 해버림~~~ / 잘못 sort 하면 섞일 수가 있다.
# 그래서 pandas가 더 편리하다.

[[ 8 12]
 [ 7  1]]


array([[ 7,  1],
       [ 8, 12]])

In [ ]:
# np.argsort(ndarray) - 0,1,2,3
org_arr = np.array([30,19,90,54]) 
org_names = np.array(['홍길','고길','마이','둘리'])  # 점수를 가지고 이름을 순위대로 알고 싶다.
                    #   0, 1   ,  2   ,  3
print(org_arr)
np.argsort(org_arr) #원본이 순서대로 정렬되었을때의 인덱스 반환

org_names[np.argsort(org_arr)][::-1] # 이럴때 사용
# np.argsort(org_arr)  : org_arr의값을 오름차순으로 정렬했을때 인덱스 배열 반환
# org_names[np.argsort(org_arr)] : ora_names를 org_arr의 오름차순 순선대로 재배열함
# [::-1] : 배열을 역순(내림차순)으로 뒤집기

#정렬하다보니까 인덱스가 이거다.


[30 19 90 54]


array(['마이', '둘리', '홍길', '고길'], dtype='<U2')

In [ ]:
# 3.6 선형대수 연산
# 행렬내적 진짜중요함
# 그냥 곱과 행렬곱은 다르다~~~ : 

# <3가지 방식으로 가능>
# 연산자 ->ndarray@ndarray -> 3.5 이후 사용가능(꿘장)
# np.dot(ndarray,ndarray) -> 편함(@보다 .연산 사용해라~)
# ndarray.dot(ndarray)

# 행렬 곱
# A * B : element wise multipication(요소별 곱)
# 언제사용? 머십러닝과 딥러닝에서 가중치(parameter,weight) 계산에 사용됨
# 내적 ->  가중치 사용

# 신경망 : 벡터와 행렬의 내적
# 벡터(data) , 행렬(선형변환,기저를 변환시킨다.)
# 결국, 신경망은 선형변환의 확산
# 행렬 : data를 가중치(W)를 가지고 변환시킨다 ,*오차가 최소가* 되게끔
# 이걸 잘 이해해야 자연어처리, 생성을 이해할 수 있음

# 딥러닝: 내적 & 차원축소



In [1]:
# 20251028
# 내적:A* B
#     2x3 3x2 ==> 결과: 2x2 (양끝인 2x2로 나옴)
# 즉) 양끝이 동일해야 내적이 가능함

# 결론)딥러닝에서 내적은 유사도, 유사도가 크면 클수록 유사하다.


# 두벡터[0,2] , [2,0] 내적했더니 0 나온다 -> 두 벡터는 절대 관련이 없다 즉, cos90 = 0


- 코사인 함수(y값:-1<x<1)
![코사인 함수 그래프](코사인함수.png)


- 스칼라: 그냥 소문자
- 벡터: 소문자로 진하게
- 행렬: 대문자

- <외국원서읽을때 표기법설명(앞부분) 먼저 보기>

#### 전치행렬

![전치행렬](전치행렬.png)
- 2X3 -> 3X2로 바뀌는것
- 왜사용?행과 열을 뒤바꾸는 연산 즉 ,행이 열이되고, 열이 행이 된다
- np.transpose() , ()안에는 ndarray
- print('\\nA 의 전치 행렬 (.T):\\n', A.T)

- 정방행렬의 전치행렬:(대각선을 기준으로 위,아래만 바꿈 근데 전치행렬에서는 이렇게 이해하면 안됨)
